### ISSUE TITLE
Cant use for NDB Memcached API due to not allowing tab in key

### ISSUE THREAD

**Issue by jonathanhartley** [bradfitz/gomemcache#106]
Using NDB API with tables with a compound key need to allow a tab (or \t) in key 
Also need to be able to specify memcached prefix as I cant find a way to specify this 
e.g. for python
 if messageok:
            try:
                mckey = "mkt:{0}\t{1}".format(data['payload']['marketId'],data['payload']['eventId'])
                mcval = "{0}\t{1}\t{2}\t{3}\t{4}\t{5}".format(data['payload']['name'],data['payload']['displayed'],data['payload']['suspended'],data['msgId'],(int(data['timestamp'])/1000),time.time())
                if mc.set(mckey.encode(), mcval.encode()):

**Comment by bradfitz** [comment]
I assume you're talking about MySQL Cluster's memcached server?

I had to Google to figure out what you were talking about, so maybe I found the wrong reference.

The memcached protocol doesn't allow tabs:

https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L48

```
Data stored by memcached is identified with the help of a key. A key
is a text string which should uniquely identify the data for clients
that are interested in storing and retrieving it.  Currently the
length limit of a key is set at 250 characters (of course, normally
clients wouldn't need to use such long keys); the key must not include
control characters or whitespace.
```

So it seems this package is working as intended.

Does MySQL require a protocol violation in their implementation of the protocol?

**Comment by bradfitz** [comment]
Timeout.
