### ISSUE TITLE
Consistent Hashing?

### ISSUE THREAD

**Issue by knight-shade** [bradfitz/gomemcache#109]
Hi @bradfitz ,
Does this client supports consistent hashing since its return CacheMiss and CacheHit randomly. I am using it in Memcached cluster in Kubernetes with 5 pods.

Regards
Abhishek

**Comment by bradfitz** [comment]
If you're using Kubernetes, presumably you're already providing a ServerSelector to NewFromSelector and that selector is the thing responsible for doing consistent hashing.

There is no built-in support for Kubernetes. Perhaps there should be (at least in a subpackage) but there isn't today.

**Comment by graywolf-at-work** [comment]
I'll plug my package here:

https://pkg.go.dev/git.sr.ht/~graywolf/gomemcache@v1.0.0/serverlist/ketama?tab=doc

It provides ServerList using ketama-compatible consistent hashing. That mean
you get the same distribution from golang, as you would get from C (well,
anything libmemcached-based).



PS: If this plug is inappropriate, feel free to delete this comment. But this
issue comes fairly up while googling how to get consistent hashing in golang,
so it seemed like it could be useful for people to have this here.
