### ISSUE TITLE
encounter fault, "Get failed memcache: unexpected line in get response: "ERROR\r\n""

### ISSUE THREAD

**Issue by clee1602** [bradfitz/gomemcache#110]
memcached version: 1.5.1
code: 
// Set
foo := &memcache.Item{Key: "home", Value: []byte("fooval")}
err := mc.Add(foo)     **// work 0k here**
if err != nil {
    fmt.Println("Set failed once", err.Error())
}
err = mc.Add(foo)    **// work 0k here**
if err != nil {
    fmt.Println("Set failed secondly", err.Error())
}

// Get
it, err := mc.Get("home")
if err != nil {
    fmt.Println("Get failed", err.Error())   **// failed here**
} else {
    if string(it.Key) == "foo" {
        fmt.Println("Add value is ", string(it.Value))
    } else {
        fmt.Println("Get failed")
    }
}

**Comment by bradfitz** [comment]
What's the bug report or question?

**Comment by clee1602** [comment]
> What's the bug report or question?

add 3 comments in the code, the last one is the question

**Comment by clee1602** [comment]
i see
cause memcache.cpp line 366
`if _, err := fmt.Fprintf(rw, "gets %s\r\n", strings.Join(keys, " ")); err != nil {`
not "gets" command, it should be "get %s..."
for memcached version: 1.5.1
thx, Pro. Brad
