### ISSUE TITLE
Better distribution in PickServer?

### ISSUE THREAD

**Issue by ricardclau** [bradfitz/gomemcache#14]
Hi, is there any particular reason to use CRC32 instead of a better distribution algorithm? 

Even MD5 or SHA1 would distribute better amongst servers, not to mention ketama based algorithms (which I don´t know if there is any proper golang implementation)

**Comment by rfratto** [comment]
Hi @bradfitz, I'm implementing a version of ServerSelector with consistent hashing (in particular, using a jump hash); is this something you'd like to accept upstream or would you prefer to keep the implementations of ServerSelector to a minimum? 

Thanks! (Also sorry for resurrecting the old issue :slightly_smiling_face:)
