### ISSUE TITLE
Unable to connect to remote memcached server

### ISSUE THREAD

**Issue by juggernauts** [bradfitz/gomemcache#29]
I am facing connect timeout error when trying to connect to my remote memcached instance but there seems to be no issue while connecting to a local instance. I'm not sure what exactly is happening but I am using the exact code as in the Readme.

**Comment by crandles** [comment]
Try increasing the `Timeout` value on your `memcache.Client`

modifying the readme example:
```
import (
        "time"
        "github.com/bradfitz/gomemcache/memcache"
)

func main() {
     mc := memcache.New("10.0.0.1:11211", "10.0.0.2:11211", "10.0.0.3:11212")
     mc.Timeout = Time.Second * 5 // Increase the client's timeout to 5 seconds
     mc.Set(&memcache.Item{Key: "foo", Value: []byte("my value")})

     it, err := mc.Get("foo")
     ...
}
```
