### ISSUE TITLE
Compilation error on go get

### ISSUE THREAD

**Issue by bkiefer88** [bradfitz/gomemcache#34]
After I run,

$ go get github.com/bradfitz/gomemcache/memcache

My shell outputs:
\# github.com/bradfitz/gomemcache/memcache
src/github.com/bradfitz/gomemcache/memcache/selector.go:92: undefined: sync.Pool

Is there something I am doing wrong or is the code broken?

I am attempting to install this on Linux Ubuntu 14.04 with Go 1.2.1 installed.

**Comment by bradfitz** [comment]
gomemcache requires Go 1.3.
