### ISSUE TITLE
How to use Codecs?

### ISSUE THREAD

**Issue by jfeldstein** [bradfitz/gomemcache#42]
Hi, 

I'm trying to store a struct, but I can find no examples of doing so with this library. 

Googling, I see examples for using `memcache.Gob.set`, but these advice seem to refer to [Appengine/memcache](https://github.com/golang/appengine/blob/master/memcache/memcache.go).

At https://github.com/bradfitz/gomemcache/blob/master/memcache/memcache.go#L150 the comments refer to using a codec to set an Item, but I can't find any reference to codecs, Gob, etc in the source. 

Is this a mistake?

**Comment by hsyan2008** [comment]
Me too.

**Comment by bradfitz** [comment]
It was never implemented.

**Comment by mingrammer** [comment]
So, there is no plan for supporting it?

**Comment by bradfitz** [comment]
Not currently.
