### ISSUE TITLE
How to use Increment/Decrement

### ISSUE THREAD

**Issue by yorkershi** [bradfitz/gomemcache#53]
Hi, can you give me a demo about how to use Increment/Decrement. Because I don't find how to set the decimal number in gomemcache.

thanks

**Comment by prasanna-sc** [comment]
This should help you I think: https://github.com/bradfitz/gomemcache/blob/master/memcache/memcache_test.go#L176-L199

**Comment by bradfitz** [comment]
See the docs:
https://godoc.org/github.com/bradfitz/gomemcache/memcache#Client.Increment
