### ISSUE TITLE
odd character limiting

### ISSUE THREAD

**Issue by stevesmoot** [bradfitz/gomemcache#57]
legalKey bounces characters with the high bit set.  But the net connection used and memcached itself ate both fine with the 8 bit characters (tho not \0 \r \n and space in keys)  See http://grokbase.com/t/danga/memcached/07ckzm4pm0/what-is-a-valid-key 
They mention updating the FAQ, tho the wiki faq seems to lack the updated text.

**Comment by qoelet** [comment]
This should have been fixed in https://github.com/bradfitz/gomemcache/pull/58.

**Comment by bradfitz** [comment]
I control only the gomemcache repo. I can't fix all the documentation on the web.
